name: flet_share_plus
description: Flet FletSharePlus control
repository: https://github.com/ayamnash/sharep/tree/main/src/flutter/flet_share_plus
version: 0.1.0
homepage: https://github.com/ayamnash/sharep

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flet: 
    git:
      url: https://github.com/flet-dev/flet.git
      ref: main
      path: packages/flet
  flutter:
    sdk: flutter
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
